#!/usr/bin/env python3
"""rank-matrix.py — build the INSTAR-Bench v3 combined matrix re-rank.

Merges the corrected critical-set runs (crit-metered + crit-gnat + crit-cli2)
into one ranked table with: pass rate, adversarial pass rate, p50 latency,
measured run cost, and effective $/Mtok (subsidy-adjusted for subscription
routes per results/SUBSIDY-ADJUSTED-COST-MODEL.md).

Writes results/instar-bench-v2/MATRIX-RERANK.md (table body; prose sections
are authored around it). Honest by construction: a route whose run is missing
is listed as PENDING, never silently dropped.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, '..', 'results', 'instar-bench-v2')
PRICES = os.path.join(HERE, '..', 'metered-prices.json')

RUNS = ['crit-metered', 'crit-gnat', 'crit-cli2']

# Effective-$/Mtok inputs (SUBSIDY-ADJUSTED-COST-MODEL.md, first-order, blended 3:1 in:out)
CLAUDE_MAX_SUBSIDY = 6.6   # measured, cache-heavy workload, Max $200
BLEND_IN, BLEND_OUT = 3, 1

def blended(inp, outp):
    return (BLEND_IN * inp + BLEND_OUT * outp) / (BLEND_IN + BLEND_OUT)

def load_prices():
    try:
        with open(PRICES) as f:
            return json.load(f)
    except Exception:
        return {}

def price_for(model, prices):
    """Find [in,out] $/Mtok for a model id in metered-prices.json (models dict or per-provider)."""
    for k, v in prices.items():
        if not isinstance(v, dict):
            continue
        i = v.get('inPerMtok'); o = v.get('outPerMtok')
        if not (isinstance(i, (int, float)) and isinstance(o, (int, float))):
            continue
        if k == model or k.split('/')[-1] == model or model.split('/')[-1] == k:
            return (i, o)
    return None

def route_rows():
    prices = load_prices()
    rows = []
    seen_runs = []
    for stamp in RUNS:
        p = os.path.join(RES, stamp, 'summary.json')
        if not os.path.exists(p):
            seen_runs.append((stamp, 'MISSING'))
            continue
        s = json.load(open(p))
        seen_runs.append((stamp, f'{len(s)} routes'))
        for route, d in s.items():
            pas = tot = ap = at = infra = 0
            for task, td in d.get('tasks', {}).items():
                for c, cd in td['cases'].items():
                    pas += cd['pass']; tot += cd['total']
                    infra += cd.get('infra', 0)
                    if cd.get('axis') == 'adversarial':
                        ap += cd['pass']; at += cd['total']
            if not tot:
                continue
            door = d.get('door', '')
            sub = bool(d.get('subsidized'))
            model = d.get('model', '')
            # effective $/Mtok
            eff = None; effnote = ''
            pr = price_for(model, prices)
            if door.startswith('metered:'):
                if pr: eff = blended(*pr); effnote = 'list'
            elif door == 'claude-code':
                if pr: eff = blended(*pr) / CLAUDE_MAX_SUBSIDY; effnote = f'list ÷ {CLAUDE_MAX_SUBSIDY}× (Max $200, cache-heavy measured)'
            elif door in ('codex-cli', 'pi-cli'):
                effnote = 'sub (ratio tbd — needs organic codex/pi traffic)'
            elif door == 'gemini-cli':
                effnote = 'consumer sub — no API entitlement (free-tier door)'
            rows.append({
                'stamp': stamp, 'route': route, 'door': door, 'model': model, 'sub': sub,
                'pass': pas, 'total': tot, 'rate': pas / tot,
                'advPass': ap, 'advTotal': at,
                'infra': infra,
                'p50': d.get('p50ms'), 'cost': d.get('costUsd'),
                'eff': eff, 'effnote': effnote,
            })
    return rows, seen_runs

def main():
    rows, seen = route_rows()
    rows.sort(key=lambda r: -r['rate'])
    out = []
    out.append('<!-- generated by rank-matrix.py — do not hand-edit the table body -->')
    out.append('')
    out.append('Runs merged: ' + ' · '.join(f'{s} ({n})' for s, n in seen))
    out.append('')
    out.append('| # | Route | Model (exact) | Door | Pass | Adversarial | p50 | Run cost | Eff $/Mtok | Infra |')
    out.append('|---|---|---|---|---|---|---|---|---|---|')
    for i, r in enumerate(rows, 1):
        eff = f"${r['eff']:.2f}" if r['eff'] is not None else '—'
        if r['effnote'] and r['eff'] is None:
            eff = r['effnote']
        adv = f"{r['advPass']}/{r['advTotal']}" if r['advTotal'] else '—'
        p50 = f"{r['p50']/1000:.1f}s" if r['p50'] else '—'
        cost = f"${r['cost']:.2f}" if isinstance(r['cost'], (int, float)) else '—'
        out.append(f"| {i} | {r['route']} | {r['model']} | {r['door'].replace('metered:metered_','')} | "
                   f"**{r['rate']:.1%}** ({r['pass']}/{r['total']}) | {adv} | {p50} | {cost} | {eff} | {r['infra'] or ''} |")
    missing = [s for s, n in seen if n == 'MISSING']
    if missing:
        out.append('')
        out.append(f"**PENDING runs (not in this table): {', '.join(missing)}** — re-run rank-matrix.py when they land.")
    body = '\n'.join(out) + '\n'
    dest = os.path.join(RES, 'MATRIX-RERANK-TABLE.md')
    open(dest, 'w').write(body)
    print(f'wrote {dest} — {len(rows)} routes')

if __name__ == '__main__':
    main()
