/**
 * IdentityRenderer — render framework-specific identity files from the
 * canonical AGENT.md source.
 *
 * Provider-portability v1.0.0: AGENT.md is the single source of truth
 * for an agent's identity (who I am, what I'm working on, who I'm
 * working with). Frameworks have their own conventions for the file
 * they auto-load at session start:
 *
 *   - Claude Code → CLAUDE.md at the project root
 *   - OpenAI Codex → AGENTS.md at the project root
 *   - Gemini CLI → GEMINI.md at the project root
 *   - (extend the renderer when new frameworks land)
 *
 * The shadow files are deterministically rendered from AGENT.md. They
 * are NOT the source of truth and should NOT be hand-edited — edits get
 * overwritten on the next render. Each shadow file ships with a header
 * banner saying so.
 *
 * This file does not write anything until you call render(); it's safe
 * to import without side effects.
 */

import fs from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Framework conventions
// ---------------------------------------------------------------------------

/**
 * Known framework conventions. Maps a framework id to the shadow filename
 * it expects at the project root.
 *
 * Extending: add a new entry here. The renderer picks it up automatically.
 */
/**
 * Display names for the relay appendix — round-19.
 *
 * The predicate selecting the hookless branch was widened in round 18 with the
 * rationale "an enumeration is what went stale" — and the enumeration INSIDE
 * that branch was left untouched: a two-way ternary defaulting to "Codex CLI".
 * So grok and pi correctly reached the branch and were then addressed as Codex.
 * Defaults to the raw id, never to another framework's name, so a new framework
 * can be unlabelled but never MISlabelled.
 */
export const FRAMEWORK_DISPLAY_NAMES: Record<string, string> = {
  'claude-code': 'Claude Code',
  'codex-cli': 'Codex CLI',
  'gemini-cli': 'Gemini CLI',
  'grok-build': 'Grok Build',
  'pi-cli': 'pi',
};

export const FRAMEWORK_SHADOW_FILES: Record<string, string> = {
  'claude-code': 'CLAUDE.md',
  'codex-cli': 'AGENTS.md',
  'gemini-cli': 'GEMINI.md',
  // Round-17 (integration): without this entry a grok-primary agent installed
  // with NO instruction file at all — CLAUDE.md is gated on claude being
  // enabled, and the shadow fallback had nothing to render. So the §10
  // awareness note reached every agent EXCEPT the ones this spec exists to
  // create, and the migrator could not repair it (migrateClaudeMd early-returns
  // when the file is absent). grok reads the shared `.agents` layout, same as
  // codex.
  'grok-build': 'AGENTS.md',
  // pi-cli has the same hole — inherited, not introduced by this spec — and is
  // fixed here rather than left as a known-and-unfixed neighbour.
  'pi-cli': 'AGENTS.md',
};

// ---------------------------------------------------------------------------
// Banner that prefixes every rendered shadow
// ---------------------------------------------------------------------------

function bannerFor(framework: string, sourceRelPath: string): string {
  return [
    `<!--`,
    `  AUTO-GENERATED by Instar's IdentityRenderer.`,
    `  Source of truth: ${sourceRelPath}`,
    `  Framework: ${framework}`,
    ``,
    `  Do NOT hand-edit this file. Edits will be overwritten on the next`,
    `  identity render. Edit the source file instead.`,
    `-->`,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

export interface RenderIdentityOptions {
  /** Project root where shadow files are written. */
  projectDir: string;
  /**
   * Frameworks to render shadows for. Defaults to every entry in
   * FRAMEWORK_SHADOW_FILES (i.e. all known frameworks). Pass a subset
   * for installs that only use one framework — saves a file write.
   */
  frameworks?: ReadonlyArray<string>;
  /**
   * Path to the canonical source. Defaults to `<projectDir>/.instar/AGENT.md`.
   * The renderer also accepts `<projectDir>/AGENT.md` (root-level) as a
   * fallback for installs that keep identity at the project root.
   */
  sourcePath?: string;
  /**
   * When true, append a framework-aware Telegram-relay reminder section to
   * the rendered shadow. Codex CLI has no SessionStart-hook analog to the
   * Claude Code shell hook that injects "MANDATORY: relay back" — so the
   * reminder has to live in AGENTS.md to survive past the first message
   * within a long-running session. Defaults to false; callers that know
   * Telegram is configured should pass true. Detection logic stays in the
   * caller — the renderer just emits the markdown.
   */
  appendTelegramRelayBlock?: boolean;
}

export interface RenderIdentityResult {
  /** Path of the source file actually read. */
  source: string;
  /** Paths of shadow files written. */
  shadowsWritten: ReadonlyArray<string>;
  /** Frameworks skipped because their shadow path was missing in the map. */
  skipped: ReadonlyArray<string>;
}

export class IdentityRendererError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'IdentityRendererError';
  }
}

/**
 * Render framework-specific shadow files from the canonical AGENT.md.
 *
 * Workflow:
 *   1. Locate source (preferred: `.instar/AGENT.md`; fallback: root `AGENT.md`).
 *   2. Read source content.
 *   3. For each requested framework, write `<projectDir>/<shadowFilename>`
 *      with the source content prefixed by the auto-generation banner.
 *
 * Throws IdentityRendererError if source can't be located or read.
 */
export function renderIdentity(options: RenderIdentityOptions): RenderIdentityResult {
  const source = resolveSource(options.projectDir, options.sourcePath);
  if (source === null) {
    throw new IdentityRendererError(
      `No canonical identity source found. Expected `
      + `${path.join(options.projectDir, '.instar', 'AGENT.md')} or `
      + `${path.join(options.projectDir, 'AGENT.md')}`,
    );
  }

  const content = fs.readFileSync(source, 'utf-8');
  const sourceRel = path.relative(options.projectDir, source);
  const requestedFrameworks = options.frameworks ?? Object.keys(FRAMEWORK_SHADOW_FILES);

  const shadowsWritten: string[] = [];
  const skipped: string[] = [];

  // Round-17: GROUP BY TARGET FILENAME before writing.
  //
  // Several frameworks legitimately share one shadow file — codex, grok and pi
  // all read the `.agents` convention's AGENTS.md. The original loop wrote once
  // PER FRAMEWORK, so the moment a second framework mapped to AGENTS.md the
  // file was written twice and the last writer won: codex agents silently lost
  // their codex banner AND their codex continuation appendix. That regression
  // was introduced by the fix for "a grok-primary agent gets no instruction
  // file at all" — a fix that broke a working framework is worse than the gap
  // it closed, and only a full-suite run on a frozen tree surfaced it.
  //
  // One file, one write, a banner naming every framework it serves, and the
  // codex appendix included whenever codex is among them.
  const byFilename = new Map<string, string[]>();
  for (const framework of requestedFrameworks) {
    const filename = FRAMEWORK_SHADOW_FILES[framework];
    if (!filename) {
      skipped.push(framework);
      continue;
    }
    const group = byFilename.get(filename);
    if (group) group.push(framework);
    else byFilename.set(filename, [framework]);
  }

  for (const [filename, frameworks] of byFilename) {
    const target = path.join(options.projectDir, filename);
    // The FIRST framework leads the banner so an existing single-framework
    // file keeps its established identity line; the rest are listed after it.
    const banner = bannerFor(frameworks.join(', '), sourceRel);
    // The relay appendix is framework-shaped; use the leading framework, which
    // for a shared file is the one whose convention the file follows.
    const relayAppendix = options.appendTelegramRelayBlock
      ? '\n\n' + buildPersistentRelayAppendix(frameworks[0]!)
      : '';
    const continuationAppendix = frameworks.includes('codex-cli')
      ? '\n\n' + buildCodexContinuationAppendix()
      : '';
    fs.writeFileSync(target, banner + content + relayAppendix + continuationAppendix, 'utf-8');
    shadowsWritten.push(target);
  }

  return { source, shadowsWritten, skipped };
}

function buildCodexContinuationAppendix(): string {
  return [
    `## Multi-step Work Continuation`,
    ``,
    `When you accept a multi-step assignment, check the local continuation capability before beginning. If it is enabled, start a bounded per-topic checklist through the authenticated local continuation API. Keep the checklist honest as work completes. The existing Codex Stop hook will continue turns only while explicit unchecked tasks remain; an empty or fully checked list ends normally.`,
    ``,
    `Do not create filler tasks. Never restart a stopped ledger. An operator stop, the hard off-switch, the duration ceiling, and the continuation-count ceiling always win. The user should never be asked to run commands or maintain the checklist—you own this lifecycle as part of accepting the work.`,
  ].join('\n');
}

/**
 * Markdown appendix that lives at the bottom of AGENTS.md / CLAUDE.md when
 * Telegram is configured. The wording mirrors the bootstrap-message helper
 * (`buildTelegramRelayBlock`) but is phrased for the system-prompt context
 * rather than the per-message turn.
 *
 * For Claude Code, the SessionStart shell hook already injects "MANDATORY:
 * After EVERY response, relay…" — but rendering it into CLAUDE.md too is
 * harmless redundancy that survives hook removal or misconfiguration.
 *
 * For Codex CLI, this is the ONLY persistent mechanism — Codex has no
 * SessionStart hook system, so the AGENTS.md content has to carry the
 * relay convention across every turn.
 */
function buildPersistentRelayAppendix(framework: string): string {
  // Codex AND Gemini have no SessionStart hook system, so the shadow file
  // (AGENTS.md / GEMINI.md) is the ONLY persistent carrier of the relay
  // convention across every turn — they get the "every turn" wording.
  // Round-18 (integration): this tested only codex/gemini, so the frameworks
  // added in round 17 (grok-build, pi-cli) rendered the CLAUDE branch — their
  // shadow told them "the SessionStart hook reinforces this", naming a hook
  // they do not have. The predicate's whole purpose is that a hookless
  // framework has no other persistent carrier, so the frameworks that most
  // need the EVERY-turn wording were the ones denied it. claude-code is the
  // sole framework with a SessionStart hook, so ask THAT question directly
  // rather than enumerating the others — an enumeration is what went stale.
  const isHooklessFramework = framework !== 'claude-code';
  return [
    `## Telegram Relay (MANDATORY)`,
    ``,
    `Every Telegram message you receive arrives prefixed \`[telegram:N "topic name" from User]\`. After responding, you MUST run this exact bash command to send the user your reply — without it, the user only sees sentinel messages and thinks you ignored them:`,
    ``,
    '```bash',
    `cat <<'EOF' | .instar/scripts/telegram-reply.sh N`,
    `Your conversational response text here.`,
    `EOF`,
    '```',
    ``,
    `(Replace \`N\` with the topic id from the prefix. If \`.instar/scripts/telegram-reply.sh\` is missing on an older install, fall back to \`.claude/scripts/telegram-reply.sh\`.)`,
    `If the response itself contains a literal \`EOF\` line or shell-sensitive content that could break the heredoc wrapper, base64-encode the response text and pipe that encoded text to \`telegram-reply.sh --stdin-base64 N\` instead.`,
    ``,
    `Rules:`,
    `- Strip the \`[telegram:N]\` prefix before interpreting the message.`,
    `- Relay ONLY conversational text — not tool output, raw logs, or internal reasoning.`,
    `- Send a short ACK first ("Got it, looking into this…"), then do the work, then send the full reply.`,
    isHooklessFramework
      ? `- ${FRAMEWORK_DISPLAY_NAMES[framework] ?? framework} specifically: this convention applies to EVERY turn in a Telegram-spawned session, not just the first one. There's no SessionStart hook reminder beyond this shadow-file section.`
      : `- Claude Code specifically: the SessionStart hook reinforces this on session start; this section is the durable backup.`,
  ].join('\n');
}

/**
 * Resolve the canonical AGENT.md path. Searches the explicit override
 * first, then `.instar/AGENT.md`, then root-level `AGENT.md`. Returns
 * null if none is found.
 */
function resolveSource(projectDir: string, override?: string): string | null {
  const candidates = [
    override,
    path.join(projectDir, '.instar', 'AGENT.md'),
    path.join(projectDir, 'AGENT.md'),
  ].filter((p): p is string => p !== undefined);

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Detect framework from an existing project layout. Used for legacy
 * installs that have CLAUDE.md but no AGENT.md — we can infer which
 * framework was configured and seed AGENT.md from the shadow content.
 *
 * Returns null when no framework-specific file is found.
 */
export function detectFrameworkFromShadowFiles(projectDir: string): string | null {
  for (const [framework, filename] of Object.entries(FRAMEWORK_SHADOW_FILES)) {
    if (fs.existsSync(path.join(projectDir, filename))) return framework;
  }
  return null;
}

/**
 * Ensure the shadow file a framework expects exists at the project root,
 * bootstrapping the canonical AGENT.md from any legacy shadow first if
 * needed.
 *
 * Lifecycle:
 *   - If `<projectDir>/<framework-shadow>` already exists, no-op.
 *   - If `.instar/AGENT.md` exists, render the requested framework's
 *     shadow from it.
 *   - If neither exists but a different shadow does (e.g., legacy
 *     CLAUDE.md without AGENT.md), bootstrap AGENT.md from that shadow,
 *     then render the requested shadow.
 *   - If nothing exists, no-op — the project has no identity content
 *     to seed from.
 *
 * Returns the path of the written shadow file, or null when the operation
 * was a no-op.
 *
 * Idempotent. Safe to call before every spawn — checks file existence
 * first and only writes when there's something useful to do.
 */
export function ensureFrameworkIdentityFile(
  projectDir: string,
  framework: string,
  options: {
    stateDir?: string;
    appendTelegramRelayBlock?: boolean;
    /** Frameworks this agent has enabled — see the round-19 membership note. */
    enabledFrameworks?: readonly string[];
  } = {},
): string | null {
  const filename = FRAMEWORK_SHADOW_FILES[framework];
  if (!filename) return null;
  const targetPath = path.join(projectDir, filename);

  // When the shadow exists, check whether the Telegram-relay appendix is
  // missing. If callers asked for it (Telegram is configured) and the
  // existing file predates the appendix, re-render so Codex sessions get
  // the durable relay convention without requiring a manual edit.
  if (fs.existsSync(targetPath)) {
    if (options.appendTelegramRelayBlock) {
      try {
        const existing = fs.readFileSync(targetPath, 'utf-8');
        if (existing.includes('## Telegram Relay (MANDATORY)')) {
          return null; // already up to date
        }
      } catch {
        // unreadable — fall through to re-render
      }
      // Fall through to render below
    } else {
      return null;
    }
  }

  // Ensure AGENT.md exists as the canonical source. If it doesn't,
  // try to bootstrap from a legacy shadow file (e.g., CLAUDE.md).
  const sourcePath = resolveSource(projectDir, options.stateDir
    ? path.join(options.stateDir, 'AGENT.md')
    : undefined);
  if (sourcePath === null) {
    const bootstrapped = bootstrapAgentMdFromShadow(projectDir, options);
    if (bootstrapped === null) return null;
  }

  // Round-18 (integration): this passed `frameworks: [framework]`, which
  // DEFEATED the round-17 grouping fix on the ONE path that actually runs.
  // `renderIdentity` groups by filename, but grouping a single-element list is
  // a no-op — so a grok or pi spawn on a codex agent still rewrote the shared
  // AGENTS.md as a single-framework file and destroyed the codex continuation
  // appendix. Verified by executing the built path: the appendix did not
  // survive, and the banner read `Framework: grok-build`.
  //
  // This is the sharper version of the round-17 lesson. That round's fix was
  // real and its test passed — but the test drove `renderIdentity` directly,
  // while production drives it through HERE. A fix verified on a path
  // production does not take is the same shape as a live proof whose input is
  // narrower than production: correct in the case exercised, absent where it
  // matters.
  //
  // Render the WHOLE GROUP that shares this framework's target file, leading
  // with the requested framework so its identity heads the banner.
  // ROUND-19: membership comes from the frameworks the agent ACTUALLY has, not
  // from the global map. Round-18 took every framework mapping to the target
  // file, which produced two defects measured on the real path:
  //   - a grok-only agent's AGENTS.md was banner-stamped with three framework
  //     names and told to rely on a Codex Stop hook it does not have;
  //   - a CODEX-only agent, which never opted into anything, had `grok-build`
  //     and `pi-cli` named in its own identity file — a dark-ship break
  //     against "an agent that does not opt in is byte-identically unaffected".
  // Writing ONE file per filename was round-18's real fix and is kept; only
  // MEMBERSHIP changes, because that is a property of the agent, not the map.
  const targetFile = FRAMEWORK_SHADOW_FILES[framework];
  // Membership = requested ∪ enabled ∪ ALREADY-EVIDENCED-IN-THE-FILE.
  //
  // The third term is load-bearing and was missing from the first draft of this
  // fix, which promptly reintroduced the round-18 clobber: scoping to the
  // agent's frameworks alone means a caller that does not pass the list
  // rewrites a shared file as single-framework and destroys the sibling's
  // appendix. Existing content is EVIDENCE that a framework is in play on this
  // agent — stronger evidence than a caller's optional argument — so it counts
  // as membership. That satisfies both constraints at once: no framework is
  // invented (dark-ship), and none already present is dropped (clobber).
  const existing = (() => {
    try {
      return targetFile ? fs.readFileSync(path.join(projectDir, targetFile), 'utf-8') : '';
    } catch (err) {
      // NOT silent — the ratchet pushed back on the first draft, correctly.
      // An unreadable shadow means the EVIDENCE term below is empty, so a
      // framework genuinely in play may be dropped from the group and its
      // content lost on the rewrite. That is the clobber this term exists to
      // prevent, so it must be visible rather than absorbed. Non-throwing:
      // degrading to "no evidence" is still safer than refusing to render an
      // identity file at all.
      const code = (err as NodeJS.ErrnoException | null)?.code;
      if (code !== 'ENOENT') {
        console.warn(
          `[identity] could not read ${targetFile} to determine framework membership `
            + `(${code ?? 'unknown'}) — a sibling framework's section may be dropped on this render.`,
        );
      }
      return '';
    }
  })();
  const inPlay = new Set<string>([
    framework,
    ...(options.enabledFrameworks ?? []),
    ...Object.keys(FRAMEWORK_SHADOW_FILES).filter((fw) => existing.includes(`Framework: ${fw}`) || existing.includes(`, ${fw}`)),
  ]);
  const owners = targetFile
    ? [
        framework,
        ...Object.entries(FRAMEWORK_SHADOW_FILES)
          .filter(([fw, file]) => file === targetFile && fw !== framework && inPlay.has(fw))
          .map(([fw]) => fw),
      ]
    : [framework];

  const result = renderIdentity({
    projectDir,
    frameworks: owners,
    sourcePath: options.stateDir
      ? path.join(options.stateDir, 'AGENT.md')
      : undefined,
    appendTelegramRelayBlock: options.appendTelegramRelayBlock,
  });
  return result.shadowsWritten[0] ?? null;
}

/**
 * Render every known framework identity shadow EXCEPT claude-code.
 *
 * `instar init` writes a rich, Claude-Code-specific CLAUDE.md via
 * `generateClaudeMd()` (the capability/instructions document — not an
 * identity render). That file legitimately owns the CLAUDE.md filename.
 * But before this helper, init wrote NOTHING for non-Claude runtimes: a
 * Codex install got a CLAUDE.md (which Codex ignores) and no AGENTS.md,
 * so identity wasn't auto-loaded until the first server spawn called
 * `ensureFrameworkIdentityFile`. This closes that init-time gap
 * additively: it produces AGENTS.md / GEMINI.md (and any future
 * non-Claude shadow) from the canonical `.instar/AGENT.md`, and
 * deliberately skips `claude-code` so the rich CLAUDE.md is never
 * clobbered.
 *
 * Idempotent and best-effort: no-ops when AGENT.md is absent, never
 * throws into the init flow (init must not fail because a shadow could
 * not be written). Returns the shadow paths written.
 */
export function renderNonClaudeIdentityShadows(
  projectDir: string,
  options: { stateDir?: string; appendTelegramRelayBlock?: boolean } = {},
): ReadonlyArray<string> {
  const nonClaude = Object.keys(FRAMEWORK_SHADOW_FILES).filter(
    (fw) => fw !== 'claude-code',
  );
  const sourcePath = options.stateDir
    ? path.join(options.stateDir, 'AGENT.md')
    : undefined;
  // No canonical source → nothing to render. Not an error at init time.
  if (resolveSource(projectDir, sourcePath) === null) return [];
  try {
    const result = renderIdentity({
      projectDir,
      frameworks: nonClaude,
      sourcePath,
      appendTelegramRelayBlock: options.appendTelegramRelayBlock,
    });
    return result.shadowsWritten;
  } catch {
    // Best-effort: a shadow render failure must never break `instar init`.
    return [];
  }
}

/**
 * Bootstrap AGENT.md from a legacy CLAUDE.md (or other shadow file).
 *
 * Used during migration when a project has a CLAUDE.md but no AGENT.md.
 * Reads the shadow, strips the auto-generation banner if present, and
 * writes the canonical AGENT.md.
 *
 * Returns the absolute path of the written AGENT.md, or null if no
 * shadow file could be found.
 */
export function bootstrapAgentMdFromShadow(
  projectDir: string,
  options: { stateDir?: string } = {},
): string | null {
  const framework = detectFrameworkFromShadowFiles(projectDir);
  if (!framework) return null;
  const shadowFilename = FRAMEWORK_SHADOW_FILES[framework]!;
  const shadowPath = path.join(projectDir, shadowFilename);

  let content = fs.readFileSync(shadowPath, 'utf-8');
  // Strip an existing banner if present so we don't end up with nested
  // "AUTO-GENERATED" notices.
  content = content.replace(/^<!--[\s\S]*?-->\n+/, '');

  const stateDir = options.stateDir ?? path.join(projectDir, '.instar');
  if (!fs.existsSync(stateDir)) {
    fs.mkdirSync(stateDir, { recursive: true });
  }
  const agentMdPath = path.join(stateDir, 'AGENT.md');
  fs.writeFileSync(agentMdPath, content, 'utf-8');
  return agentMdPath;
}
