/**
 * standardsRegistryPath — the ONLY place a standards-registry path is constructed.
 *
 * The constitution (`docs/STANDARDS-REGISTRY.md`) is authored in the repo and
 * shipped as a BUILD ARTIFACT under `dist/data/`, generated by
 * `scripts/generate-standards-registry-asset.mjs` and packed with the compiled
 * code that reads it.
 *
 * WHY THIS MODULE EXISTS (the defect it closes, measured 2026-07-26):
 * both readers used to resolve `<projectDir>/docs/STANDARDS-REGISTRY.md` — the
 * agent-home SNAPSHOT. That file is written once at install and never refreshed,
 * because `docs/` appears in ZERO of the 9,835 files `npm pack` produces (re-measured 2026-07-28). The
 * enforcement-coverage audit was therefore grading a May-24 copy carrying 22
 * standards while the authored document carried 81, and the refresh entry in
 * `PostUpdateMigrator.migrateFeatureMaturationGate` read a bundled path that
 * exists in no published install — throwing into `result.errors` every run,
 * where nothing looks. No deployed agent could ever receive an amended standard.
 *
 * The fix is to stop copying: the reader and its data ship in the same package
 * version, so "this code is running but its data is missing" is only ever a
 * BROKEN install, never an old one.
 *
 * Spec: docs/specs/standards-registry-snapshot-refresh.md §3.
 */

import fs from 'node:fs';
import { join as pathJoin } from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { parseStandardsRegistryDetailed } from './StandardsRegistryParser.js';

/**
 * The resolver's contract is a typed result — NOT a throw, and NOT a nullable
 * string.
 *
 * A discriminated union is chosen over a throw precisely because a throw is what
 * the original defect turned into a fabricated answer: an exception invites a
 * `catch` that guesses, while a union forces the caller to name the non-usable
 * case. Callers render `usable: false` as an honest untrustworthy report and MUST
 * NOT crash the endpoint or turn it into a 500.
 */
export type RegistryResolution =
  | {
      usable: true;
      path: string;
      sha256: string;
      articleCount: number;
      /**
       * The bytes this resolution ALREADY read, decoded once.
       *
       * Consumers must read this rather than re-opening `path`. Before it existed
       * the same file was read and parsed three times per coverage call — once
       * here, once in `computeInputHash`, once in `computeCoverage` — and each
       * re-read was also a TOCTOU seam: the integrity check below applied to bytes
       * that a later reader might not get. Carrying the bytes collapses both.
       */
      markdown: string;
      /** How this resolution's currency was established — see `RegistryIntegrity`. */
      integrity: RegistryIntegrity;
    }
  | {
      usable: false;
      reason: 'broken-install' | 'integrity-mismatch' | 'invalid-meta' | 'unexpected-error';
      detail: string;
      observed?: { path?: string; sha256?: string; articleCount?: number };
    };

/**
 * WHAT ESTABLISHED THAT THESE BYTES ARE THE ONES THIS BUILD SHIPS.
 *
 * This type exists because the audit used to report `verified` from a comparison
 * that could not fail (ACT-1426). The route handed the auditor
 * `expectation.sha256 = resolution.sha256`, and the auditor compared it against a
 * re-hash of the same file — but `resolution.sha256` is only ever returned past
 * the `meta.sha256 !== observedSha` guard below, so all three values are the same
 * number BY CONSTRUCTION. The comparison was ceremony, and `verified` was granted
 * by ceremony.
 *
 * The honest repair is not a better comparison downstream — there is no
 * independent runtime expectation to compare against, and inventing one would be
 * theatre of a different shape. It is to state the basis the resolver ACTUALLY
 * established and let the consumer report on that basis by name.
 *
 * **THE SHA PAIR ALONE DOES NOT EARN THE NAME, and an earlier revision of this file
 * claimed it did.** The generator writes the registry and its meta on ADJACENT lines
 * in one loop, so the pair is self-consistent forever, however old it is relative to
 * the code. `tsc` on its own (a `pnpm dev` watch) recompiles `dist/core/*.js` without
 * re-running the generator — so "current reader, arbitrarily old constitution,
 * internally consistent" was fully representable and resolved as `verified`. That is
 * the ACT-1426 tautology one radius out: two operands that are no longer the same
 * number, but which one script writes in one pass, so they can disagree only if a
 * human hand-edits exactly one file.
 *
 * The basis rests on three operands — the sha pair, the **package version stamp**, and
 * the **article count** — and an earlier draft claimed TWO of them were not derived from
 * the registry bytes. That was wrong, and it is the THIRD time this design overclaimed in
 * the same direction: the generator parses those same bytes to produce `articleCount` and
 * the resolver reparses them with the same parser, so in production the count cannot
 * disagree. **Exactly one operand here is not bytes-derived: the version stamp** — and it
 * only disagrees when a version bump lands without a rebuild, which is neither the dev
 * scenario named above nor the publish path.
 *
 * What the count actually catches is worth stating precisely rather than dropping: parser
 * drift between the `dist/` parser that generated the meta and the one reading it now.
 * That is a real fault and a narrow one.
 *
 * **The operand that closes the gap lives in the AUDITOR, not here** —
 * `compareAgainstAuthoredSource`, which in an instar source tree compares the graded bytes
 * against the authored constitution. It is the one input the build that wrote the asset
 * did not write. It is unanswerable in a published install (no authored source) and
 * deliberately not attempted in an agent home (where that file is a mirror of the asset,
 * so the comparison would be a fourth tautology). What that establishes is CURRENCY: this data shipped with this
 * code. It is still NOT a runtime check against the authored source (that equality is
 * asserted in the unit suite at BUILD time), and still NOT adversarial — anyone who
 * can edit the asset can edit the meta beside it.
 */
export type RegistryIntegrity =
  | {
      basis: 'packed-meta-match';
      /** The sha the same-build meta declared — equal to the resolution's `sha256`. */
      metaSha256: string;
      /** The article count the same-build meta declared. */
      metaArticleCount: number | null;
      /** Article headings the shared parser saw in THESE bytes. `null` = it could not parse them. */
      observedArticleCount: number | null;
      /**
       * `true` / `false` / `null` when the comparison is unanswerable (either side
       * unknown). Unknown is NOT a match and is NOT a mismatch, and reporting it as
       * either is the absence-reads-as-presence failure this module exists to remove.
       *
       * **A `false` here DOWNGRADES the verdict** (see `earnsVerified`). An earlier
       * revision made this diagnostic-only, reasoning that a parser rule change could
       * otherwise take the audit offline. Review falsified the premise: the downgrade
       * path is `unverified`, not a 503 — the report is still produced and the ratio
       * still computed. Weighed against a harm that does not exist, the rule was
       * discarding the system's ONLY genuine cross-artifact signal. In production both
       * counts come from one compiled parser over one buffer, so a disagreement is not
       * "parser drift" — it is evidence the two artifacts came from different builds.
       * Routing that into prose guaranteed that the one thing which could contradict
       * `verified` never would.
       */
      articleCountMatchesMeta: boolean | null;
      /** The package version this asset was generated FOR (absent in pre-2026-07-28 assets). */
      metaPackageVersion: string | null;
      /** The version of the package currently executing this code. */
      runningPackageVersion: string | null;
      /**
       * The operand the generator did NOT derive from the registry bytes — the whole
       * reason this type can make a falsifiable claim. `false` downgrades the verdict.
       * `null` when either side is unknown (an asset generated before the stamp).
       */
      packageVersionMatches: boolean | null;
    }
  | {
      /**
       * A caller named the path outright (test fixtures). There is no same-build
       * expectation to check it against, so a consumer must NOT report `verified`.
       */
      basis: 'caller-supplied-path';
    };

/**
 * The single predicate that decides whether a resolution's integrity basis is strong
 * enough for a consumer to report `verified`.
 *
 * It lives HERE, next to the type, rather than in the auditor, because the auditor is
 * ratcheted against performing comparisons of its own — and without a named home the
 * "which operands must agree" rule would drift back into a consumer as ad-hoc
 * conditionals. One predicate, one place, every downgrade named.
 */
export function earnsVerified(integrity: RegistryIntegrity | undefined): { verified: boolean; reason: string } {
  if (!integrity) return { verified: false, reason: 'no integrity basis was supplied with this registry' };
  if (integrity.basis === 'caller-supplied-path') {
    return { verified: false, reason: 'this registry came from a caller-supplied path, which has no same-build meta beside it' };
  }
  if (integrity.packageVersionMatches === false) {
    return {
      verified: false,
      reason:
        `the packed constitution was generated for package version ${integrity.metaPackageVersion} but the ` +
        `code reading it is version ${integrity.runningPackageVersion} — CROSS-VERSION skew. Stated at that ` +
        `strength deliberately: version equality does NOT prove the asset is current, because a stale asset ` +
        `generated at the same version still matches. What covers that is the authored-source comparison ` +
        `where it can run, and build discipline everywhere else. The registry is internally consistent here, ` +
        `which is exactly why the sha pair cannot see it`,
    };
  }
  if (integrity.packageVersionMatches === null) {
    return {
      verified: false,
      reason:
        'the packed constitution carries no package-version stamp, so nothing establishes it was generated ' +
        'for THIS build — an asset predating the stamp, or a partial generation',
    };
  }
  if (integrity.articleCountMatchesMeta === false) {
    return {
      verified: false,
      reason:
        `the shared parser read ${integrity.observedArticleCount} article headings from these bytes where the ` +
        `meta generated beside them recorded ${integrity.metaArticleCount} — the two artifacts disagree about ` +
        `their own content, which is evidence they came from different builds`,
    };
  }
  if (integrity.articleCountMatchesMeta === null) {
    return {
      verified: false,
      reason:
        'the article count could not be compared (the parser could not read these bytes, or the meta records ' +
        'no count), so one of the three operands is simply unknown',
    };
  }
  return {
    verified: true,
    reason:
      `the resolver matched these bytes against the integrity meta generated beside them ` +
      `(sha ${integrity.metaSha256.slice(0, 12)}), confirmed the asset was generated for the running package ` +
      `version ${integrity.runningPackageVersion}, and confirmed both artifacts agree on ` +
      `${integrity.metaArticleCount} articles. That establishes CURRENCY — this data shipped with the code ` +
      `reading it. It is not a runtime check against the authored source, and it is not tamper-resistant`,
  };
}

/** Shape of `dist/data/standards-registry.meta.json`, generated in the same build. */
export interface StandardsRegistryMeta {
  /** sha256 of the registry bytes generated alongside this meta. */
  sha256: string;
  /**
   * Article headings the shared parser saw. One of the three operands `earnsVerified` walks:
   * a disagreement with the observed count DOWNGRADES `verified` → `unverified` (never
   * `untrustworthy`, never a 503 — the audit stays online, only the currency claim is withheld).
   *
   * This said "DIAGNOSTIC ONLY (never invalidates)" until round 10. That was an earlier
   * draft's design, reversed in review, and the sentence outlived it HERE — 32 lines from the
   * predicate that acts on it. Eighth instance of this class in this change, and the first
   * inside `src/`: the spec, §0's table and the decision-point row were all corrected while
   * the code's own comment kept saying the opposite. Read `earnsVerified`, not this.
   */
  articleCount: number;
  /** Repo-relative path of the authored document this was generated from. */
  generatedFrom: string;
  /**
   * The package version this asset was generated FOR. Optional in the type because
   * an asset built before 2026-07-28 will not carry it — its absence is reported as
   * an unknown operand (never as a match), so an unstamped asset cannot earn
   * `verified` by silence.
   */
  packageVersion?: string;
}

/**
 * The ONE place that knows where a mirror of the constitution goes on an agent.
 *
 * The migrator needs two paths this module must still own: the packed asset inside
 * the BUNDLED (incoming) package — which is not this module's own `../data`, because
 * the migrator is copying from a different installation root — and the agent-home
 * document every prose pointer names. Exposing them as a function keeps the
 * import-boundary rule intact ("exactly one module may own registry location") while
 * letting the migrator do its job; the alternative was a path literal in the migrator,
 * which the boundary test correctly refuses.
 */
export function registryMirrorPaths(
  bundledRoot: string,
  agentRoot: string,
): { bundled: string; target: string; skip?: string } {
  // REFUSE the mirror when the target IS the authored source.
  //
  // Review caught this as a destructive consequence of `alwaysOverwrite`: if the
  // agent's project dir is an instar checkout, `docs/STANDARDS-REGISTRY.md` is not a
  // stale copy to refresh — it is the document everything else is generated FROM. An
  // older installed package would silently revert the authored constitution, and the
  // migrator's backup is written only `if (!existsSync(backup))`, so the second
  // overwrite would destroy it with nothing kept.
  //
  // The probe is the same one the auditor uses to decide whether a tree can answer for
  // its own guards, for the same reason: an instar source tree is a different kind of
  // place than an agent home, and the difference is exactly what makes the mirror
  // correct in one and destructive in the other.
  const authored = holdsAuthoredConstitution(agentRoot);
  return {
    bundled: pathJoin(bundledRoot, 'dist', 'data', REGISTRY_ASSET_BASENAME),
    // The agent-home path is not a reader anymore — the machine readers use the packed
    // asset. It is the path every prose pointer shipped to agents still names (the
    // CLAUDE.md sections, spec-converge, instar-dev, iterative-converging-audit), so
    // it must hold the CURRENT constitution or the agent reads a stale rulebook while
    // the instruments read a fresh one.
    target: pathJoin(agentRoot, 'docs', 'STANDARDS-REGISTRY.md'),
    ...(authored
      ? { skip: 'target is the AUTHORED constitution of an instar source tree — mirroring would revert it' }
      : {}),
  };
}

/**
 * Is `docs/STANDARDS-REGISTRY.md` in this directory the AUTHORED ORIGINAL, as opposed to
 * a mirror of the packed asset?
 *
 * **NOT the same question as `SourceTreeGuard.isInstarSourceTree`, and the name says so
 * now.** An earlier version of this function carried that exact name, which was a trap:
 * review reasonably said "delegate to the canonical one". Measuring first showed that
 * would BREAK the feature — the canonical guard returns TRUE for the agent home, because
 * that home carries a `.instar-source-tree` marker, so delegating would refuse the mirror
 * precisely where the mirror has to land.
 *
 * The two answer different questions and both answers are right for their own:
 *   - `SourceTreeGuard.isInstarSourceTree` — "is this a tree destructive managers must
 *     never touch?" Deliberately over-inclusive, fail-closed, three OR'd layers.
 *   - THIS — "is that file here the original everything else is generated from?" A mirror
 *     lands in a non-repository; the original lives in a checkout.
 *
 * Same-named functions with different semantics are how a future reader picks the wrong
 * one, so this one is renamed rather than aligned.
 *
 * All three markers required. A partial match is not an instar checkout, and guessing
 * wrong in the permissive direction is the destructive one.
 */
export function readAuthoredConstitution(projectDir: string): string | null {
  // The authored document's location is registry-location knowledge, so it lives here
  // with the rest of it — the import-boundary test enforces that exactly one module owns
  // it, and correctly objected when the auditor built this path itself.
  if (!holdsAuthoredConstitution(projectDir)) return null;
  try {
    return fs.readFileSync(pathJoin(projectDir, 'docs', 'STANDARDS-REGISTRY.md'), 'utf-8');
  } catch {
    return null;
  }
}

export function holdsAuthoredConstitution(dir: string): boolean {
  // Markers that PREDATE this change, deliberately.
  //
  // The previous version keyed on `scripts/generate-standards-registry-asset.mjs` — a
  // file THIS BRANCH introduces. Review checked `git log origin/main` for it and found
  // nothing, which means every checkout at a pre-merge commit (a release branch, a
  // bisect, an older worktree, any branch carrying unmerged constitution edits) would
  // have failed OPEN: judged "not a source tree", and therefore had its AUTHORED
  // constitution overwritten by the ungated mirror. A refusal that depends on the change
  // being present cannot protect the trees that do not have it yet — which is precisely
  // the population that most needs protecting.
  //
  // `.git` + `docs/specs/` + `src/core` all predate the change by months.
  //
  // MEASURED, because the reasoning above would have been wrong on its own: an agent home
  // carries BOTH `src/core` and `docs/specs`. So those two discriminate nothing in the
  // case that matters — **`.git` is doing all the work**, and the other two are defence
  // against a directory that merely resembles a checkout. Verified on the real pair:
  // agent home → not a source tree → mirror ALLOWED; this worktree → source tree →
  // mirror REFUSED. (A git WORKTREE has `.git` as a FILE, not a directory; `existsSync`
  // is true for both, which is what makes this work here at all.)
  //
  // Failure direction if someone `git init`s their agent home: the mirror is REFUSED, so
  // they stop receiving constitution refreshes. That is the safe direction — no
  // destruction, only a missed update — and it is the reason to prefer this marker over
  // one that fails open.
  //
  // Package identity is NOT used: an agent home has no `package.json` at all, and an
  // earlier version requiring it made a sibling probe return false forever on the only
  // deployment where this surface is live.
  // ORDER REVERSED (round-6 finding). An earlier version short-circuited on target
  // absence FIRST, reasoning "nothing to destroy". That is true of BYTES and false of
  // WORKING-TREE STATE: a genuine checkout whose `docs/STANDARDS-REGISTRY.md` is
  // transiently absent — mid-rebase, a merge-conflict delete, a `git rm` in flight — read
  // as not-authored, so the migrator took its `!existsSync(target)` branch and INSTALLED
  // the packed asset (possibly older bytes) at the authored path, where git presents it
  // as a restore someone can commit. That inverts this module's own fail-closed rule at
  // the exact branch it was added for.
  //
  // Markers decide FIRST. If this is a checkout, refuse whether or not the file is there.

  // `statSync`, not `existsSync`. `existsSync` swallows EVERY error and returns false, so
  // a permissions failure is indistinguishable from an absent directory — which made an
  // earlier `catch` here UNREACHABLE. It read as a fail-closed guard and could not fire:
  // the same cannot-fire shape this whole change exists to remove, written INTO the guard
  // against it. Caught by probing an unreadable tree and watching the mirror be ALLOWED.
  const present = (...rel: string[]): boolean => {
    try { fs.statSync(pathJoin(dir, ...rel)); return true; }
    catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return false;
      throw err; // EACCES and friends are UNCERTAINTY, not absence
    }
  };
  try {
    if (!present('src', 'core')) return false;
    if (!present('docs', 'specs')) return false;
    // A checkout is a checkout regardless of whether the constitution is currently on
    // disk — the transient-absence window is precisely when the permissive answer is
    // most dangerous.
    return present('.git');
  } catch {
    // FAIL CLOSED: a directory we cannot READ (EACCES on a marker) is treated as authored,
    // so the mirror refuses. Note this is now unconditional — the earlier wording said it
    // applied only to a tree "whose constitution DOES exist", which described the
    // target-existence probe the marker-first reorder above DELETED. Refusing a tree we
    // cannot classify costs an un-mirrored constitution; the other direction overwrites an
    // authored one. Reachable only via a genuine permissions failure, which is why the
    // `present` helper distinguishes EACCES from ENOENT rather than using `existsSync`.
    return true;
  }
}

export const REGISTRY_ASSET_BASENAME = 'standards-registry.md';
export const REGISTRY_META_BASENAME = 'standards-registry.meta.json';

/** sha256 of a buffer, lowercase hex — the single integrity primitive. */
export function sha256(bytes: Buffer | string): string {
  return crypto.createHash('sha256').update(bytes).digest('hex');
}

/**
 * Count article headings with the SAME parser the generator and the release
 * verifier use. One parser, three consumers: that is what makes a
 * hash-match/count-mismatch state unreachable (identical bytes parse
 * identically) and stops parser drift from producing a spurious diagnostic.
 */
export function countRegistryArticles(markdown: string): number {
  return parseStandardsRegistryDetailed(markdown).diagnostics.articleHeadings;
}

/**
 * Resolve the packed runtime registry.
 *
 * This module compiles to `dist/core/standardsRegistryPath.js`, so `../data/…`
 * resolves to `dist/data/…` — the same place in a built source checkout and in an
 * installed `node_modules/instar/`, because the layout is identical in both. No
 * `../..` counting, no upward walking, no `package.json` name match, no
 * `projectDir` candidate, and NO FALLBACK: there is nothing else to fall back to.
 *
 * Never throws.
 */
/**
 * PRODUCTION resolver. Takes NO argument — deliberately.
 *
 * Cross-model review raised the optional-path parameter in THREE consecutive
 * rounds. Each time I narrowed the policy (regex assertions, then a VITEST gate on
 * the route) and each time the reviewer correctly pointed out the same thing: an
 * optional `explicitPath` on the primary API is a footgun regardless of who
 * currently passes it, because the NEXT caller can. Removing the parameter is the
 * only answer that does not depend on future authors behaving. Fixture resolution
 * now lives in the separately-named `resolveStandardsRegistryFromPath`, which no
 * `src/` callsite may reference (asserted).
 */
export function resolveStandardsRegistry(): RegistryResolution {
  return resolveStandardsRegistryGuarded(undefined);
}

/**
 * TEST-ONLY fixture resolution. Named so a production import is self-evidently
 * wrong at the callsite, and asserted to have zero `src/` callers.
 */
export function resolveStandardsRegistryFromPath(explicitPath: string): RegistryResolution {
  return resolveStandardsRegistryGuarded(explicitPath);
}

/**
 * The version of the package currently executing this code.
 *
 * `dist/core/…` → `../../package.json`, the same module-relative reasoning the asset
 * resolution uses and for the same reason: the layout is identical in a built source
 * checkout and in an installed `node_modules/instar/`. Returns `null` rather than
 * throwing or guessing — an unknown version is reported as an unknown operand, which
 * does not earn `verified`.
 */
function readRunningPackageVersion(): string | null {
  try {
    const pkgPath = fileURLToPath(new URL('../../package.json', import.meta.url));
    const version = (JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as { version?: unknown }).version;
    return typeof version === 'string' && version.length > 0 ? version : null;
  } catch {
    return null;
  }
}

function resolveStandardsRegistryGuarded(explicitPath?: string): RegistryResolution {
  // Catch-all boundary. "Never throws" was an API INTENT until cross-model review
  // round 2 pointed out it was under-specified: hashing, encoding, permissions and
  // parser failures can all throw from paths the inner handlers do not individually
  // guard. Making it an implementation INVARIANT rather than a property someone has
  // to re-verify by inspection is the difference between a promise and a guarantee —
  // and a resolver that throws is exactly what invites the guessing `catch` this
  // whole module exists to prevent.
  try {
    return resolveStandardsRegistryInner(explicitPath);
  } catch (err) {
    return {
      usable: false,
      // NOT 'broken-install' (round-7 finding): an unexpected throw is most likely a
      // CODE regression, and labelling it as an install problem sends the reader to
      // reinstall instead of to the bug. Mislabelling a failure is the same class of
      // dishonesty as hiding one.
      reason: 'unexpected-error',
      detail:
        'the registry could not be resolved due to an unexpected error: ' +
        `${err instanceof Error ? err.message : String(err)}`,
      ...(explicitPath ? { observed: { path: explicitPath } } : {}),
    };
  }
}

function resolveStandardsRegistryInner(explicitPath?: string): RegistryResolution {
  // An EXPLICIT caller-named path is honoured verbatim. This is not a fallback and
  // does not weaken the guarantee: the defect was that readers reached a stale copy
  // *implicitly*, by constructing `<projectDir>/docs/…` on their own with no one
  // naming it. A path a caller states outright is the opposite of that — it is
  // visible at the callsite, it is never tried "as well as" the packed asset, and
  // there is still no candidate chain anywhere.
  //
  // It exists because the route-level tests need a CONTROLLED constitution (an
  // empty one, a three-article one, one with a known gap) to assert semantic
  // boundaries against. Without it those tests could only run against the live
  // 81-article document, which is both brittle and untestable at the boundaries.
  // No production callsite passes this.
  if (explicitPath !== undefined) {
    let bytes: Buffer;
    try {
      bytes = fs.readFileSync(explicitPath);
    } catch {
      return {
        usable: false,
        reason: 'broken-install',
        detail: `the explicitly-supplied registry path does not exist: ${explicitPath}`,
        observed: { path: explicitPath },
      };
    }
    const markdown = bytes.toString('utf-8');
    let count: number | undefined;
    try { count = countRegistryArticles(markdown); } catch { /* diagnostic only */ }
    return {
      usable: true,
      path: explicitPath,
      sha256: sha256(bytes),
      articleCount: count ?? 0,
      markdown,
      integrity: { basis: 'caller-supplied-path' },
    };
  }

  let registryPath: string;
  let metaPath: string;
  try {
    registryPath = fileURLToPath(new URL(`../data/${REGISTRY_ASSET_BASENAME}`, import.meta.url));
    metaPath = fileURLToPath(new URL(`../data/${REGISTRY_META_BASENAME}`, import.meta.url));
  } catch (err) {
    return {
      usable: false,
      reason: 'broken-install',
      detail: `could not resolve the packed registry location: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  let registryBytes: Buffer;
  try {
    registryBytes = fs.readFileSync(registryPath);
  } catch {
    return {
      usable: false,
      reason: 'broken-install',
      detail:
        `the packed registry is absent at ${registryPath}. It is generated by ` +
        'scripts/generate-standards-registry-asset.mjs during `npm run build` and ships inside ' +
        'dist/. Its absence means an incomplete build or an incomplete install — NOT an old one.',
      observed: { path: registryPath },
    };
  }

  const runningPackageVersion = readRunningPackageVersion();
  const registryMarkdown = registryBytes.toString('utf-8');
  const observedSha = sha256(registryBytes);
  let observedCount: number | undefined;
  try {
    observedCount = countRegistryArticles(registryMarkdown);
  } catch {
    /* diagnostic only — a parse failure must not decide validity */
  }

  let meta: StandardsRegistryMeta;
  try {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8')) as StandardsRegistryMeta;
  } catch {
    // Meta-absent is INVALID rather than "unverified": the meta ships beside the
    // code that reads it, so its absence is an incomplete install — and "I could
    // not verify" reported as usable is precisely the absence-reads-as-presence
    // failure this whole change exists to remove.
    return {
      usable: false,
      reason: 'invalid-meta',
      detail:
        `the packed registry is present but its integrity meta is absent or unreadable at ${metaPath}. ` +
        'Without the meta there is no way to confirm these bytes are the ones this build shipped.',
      observed: { path: registryPath, sha256: observedSha, articleCount: observedCount },
    };
  }

  if (typeof meta.sha256 !== 'string' || meta.sha256.length !== 64) {
    return {
      usable: false,
      reason: 'invalid-meta',
      detail: `the integrity meta at ${metaPath} carries no usable sha256 field.`,
      observed: { path: registryPath, sha256: observedSha, articleCount: observedCount },
    };
  }

  if (meta.sha256 !== observedSha) {
    // PACKAGE SELF-CONSISTENCY, not tamper resistance — stated precisely because
    // the earlier wording overclaimed (cross-model review round 2, finding 3). A
    // sha match proves these bytes came from the same build as the meta beside
    // them. It does NOT prove either matches the authored source at runtime, and it
    // is NOT adversarial: anyone who can edit the registry can edit the meta. The
    // authored-source equality is asserted in the unit suite at BUILD time; this
    // check catches a stale dist, a wrong lifecycle order, or a hand-edited
    // artifact. A reword regenerates both in the same pass, so there is no
    // legitimate mismatch to tolerate.
    return {
      usable: false,
      reason: 'integrity-mismatch',
      detail:
        `the packed registry does not match the integrity meta generated alongside it ` +
        `(expected sha256 ${meta.sha256}, found ${observedSha}` +
        (observedCount !== undefined && typeof meta.articleCount === 'number'
          ? `; parsed ${observedCount} article headings, meta expected ${meta.articleCount}`
          : '') +
        '). Rebuild; do not edit dist/ by hand.',
      observed: { path: registryPath, sha256: observedSha, articleCount: observedCount },
    };
  }

  return {
    usable: true,
    path: registryPath,
    sha256: observedSha,
    markdown: registryMarkdown,
    integrity: {
      // Three operands, not one. Reaching this line required `meta.sha256 ===
      // observedSha`, but that pair is written by one script in one pass and so
      // cannot see a stale asset. The version stamp and the article count are the
      // operands the generator did NOT derive from these bytes; `earnsVerified`
      // requires all three, and names whichever one fails.
      basis: 'packed-meta-match',
      metaSha256: meta.sha256,
      metaArticleCount: typeof meta.articleCount === 'number' ? meta.articleCount : null,
      observedArticleCount: observedCount ?? null,
      articleCountMatchesMeta:
        typeof meta.articleCount === 'number' && observedCount !== undefined
          ? observedCount === meta.articleCount
          // Unknown on either side is neither a match nor a mismatch. Reporting it
          // as either is the absence-reads-as-presence failure this module exists
          // to remove — so it is `null`, and `null` does not earn `verified`.
          : null,
      metaPackageVersion: typeof meta.packageVersion === 'string' ? meta.packageVersion : null,
      runningPackageVersion,
      packageVersionMatches:
        typeof meta.packageVersion === 'string' && runningPackageVersion !== null
          ? meta.packageVersion === runningPackageVersion
          : null,
    },
    // `articleCount` DOWNGRADES on disagreement — an operand of `earnsVerified`, not a
    // diagnostic. (This comment asserted the reverse until round 10; see the doc-comment on
    // `RegistryIntegrity.articleCount` for why the stale sentence survived in two places.)
    //
    // The reasoning that once justified diagnostic-only is kept, because it is the argument
    // someone will make again: the count derives from parser behaviour, so a parser bug could
    // take the audit offline over byte-valid bytes. That harm does not exist — the downgrade
    // path is `unverified`, not a 503 — and the rule was discarding the only cross-artifact
    // signal capable of contradicting `verified`.
    //
    // It also earns its place for legibility: a reader sees "parsed 22, expected 81" rather
    // than two hex strings.
    articleCount: observedCount ?? meta.articleCount,
  };
}
