/**
 * Unit tests for the analysis-paralysis-guard PostToolUse hook.
 *
 * The hook is a Node.js script generated by PostUpdateMigrator.getAnalysisParalysisGuardHook().
 * We test it by:
 *   1. Writing the generated script to a temp file
 *   2. Piping JSON tool-call payloads into it
 *   3. Asserting the JSON it writes to stdout matches the expected decision
 *
 * Covers:
 *   - Single read-only tool call → no warning (under threshold)
 *   - 5 read-only calls in a row → warning ("ANALYSIS-PARALYSIS DETECTED")
 *   - Action tool resets the counter
 *   - Different sessions tracked independently
 *   - Tool not in either list passes through unchanged
 *   - Errors never block (always exit 0)
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execSync, spawnSync } from 'node:child_process';
import { PostUpdateMigrator } from '../../src/core/PostUpdateMigrator.js';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

let tempProjectDir: string;
let hookPath: string;

beforeEach(() => {
  tempProjectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'analysis-paralysis-test-'));
  fs.mkdirSync(path.join(tempProjectDir, '.instar', 'state'), { recursive: true });

  // Materialize the hook script from the PostUpdateMigrator generator.
  // This is the same content `instar upgrade` writes to .instar/hooks/instar/.
  const migrator = new PostUpdateMigrator(tempProjectDir);
  const hookContent = migrator.getHookContent('analysis-paralysis-guard');
  hookPath = path.join(tempProjectDir, 'analysis-paralysis-guard.js');
  fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
});

afterEach(() => {
  SafeFsExecutor.safeRmSync(tempProjectDir, { recursive: true, force: true, operation: 'tests/unit/analysis-paralysis-guard.test.ts' });
});

function runHook(payload: object): { stdout: string; stderr: string; status: number | null } {
  const result = spawnSync('node', [hookPath], {
    input: JSON.stringify(payload),
    encoding: 'utf-8',
    env: { ...process.env, CLAUDE_PROJECT_DIR: tempProjectDir },
  });
  return { stdout: result.stdout, stderr: result.stderr, status: result.status };
}

function parseDecision(stdout: string): { decision?: string; additionalContext?: string } {
  if (!stdout.trim()) return {};
  try {
    return JSON.parse(stdout);
  } catch {
    return {};
  }
}

describe('analysis-paralysis-guard hook', () => {
  it('a single read-only tool call does not warn', () => {
    const r = runHook({ session_id: 's1', tool_name: 'Read', tool_input: { file_path: '/a' } });
    expect(r.status).toBe(0);
    const dec = parseDecision(r.stdout);
    expect(dec.additionalContext).toBeUndefined();
  });

  it('5 read-only calls in a row trigger the warning', () => {
    for (let i = 0; i < 4; i++) {
      runHook({ session_id: 's1', tool_name: 'Read', tool_input: { file_path: `/file${i}` } });
    }
    const r = runHook({ session_id: 's1', tool_name: 'Read', tool_input: { file_path: '/file4' } });
    expect(r.status).toBe(0);
    const dec = parseDecision(r.stdout);
    expect(dec.decision).toBe('approve');
    expect(dec.additionalContext).toContain('ANALYSIS-PARALYSIS DETECTED');
    expect(dec.additionalContext).toContain('5 consecutive');
  });

  it('an action tool (Edit) resets the counter', () => {
    for (let i = 0; i < 4; i++) {
      runHook({ session_id: 's1', tool_name: 'Grep', tool_input: { pattern: 'x' } });
    }
    runHook({ session_id: 's1', tool_name: 'Edit', tool_input: {} });

    // Next 4 reads should NOT trigger (counter reset)
    for (let i = 0; i < 4; i++) {
      const r = runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
      const dec = parseDecision(r.stdout);
      expect(dec.additionalContext).toBeUndefined();
    }
  });

  it('Bash and Write also reset the counter', () => {
    for (let i = 0; i < 4; i++) runHook({ session_id: 's1', tool_name: 'Glob', tool_input: {} });
    runHook({ session_id: 's1', tool_name: 'Bash', tool_input: { command: 'echo' } });

    for (let i = 0; i < 4; i++) {
      const r = runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
      expect(parseDecision(r.stdout).additionalContext).toBeUndefined();
    }
  });

  it('different sessions are tracked independently', () => {
    for (let i = 0; i < 4; i++) runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });

    // 4 reads on a DIFFERENT session — should NOT trigger
    for (let i = 0; i < 4; i++) {
      const r = runHook({ session_id: 's2', tool_name: 'Read', tool_input: {} });
      expect(parseDecision(r.stdout).additionalContext).toBeUndefined();
    }

    // The 5th read on s1 should still trigger (its counter is at 4)
    const r = runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
    expect(parseDecision(r.stdout).additionalContext).toContain('ANALYSIS-PARALYSIS');
  });

  it('a tool that is neither read-only nor action passes through silently', () => {
    const r = runHook({ session_id: 's1', tool_name: 'TaskCreate', tool_input: {} });
    expect(r.status).toBe(0);
    expect(parseDecision(r.stdout).additionalContext).toBeUndefined();
  });

  it('malformed input never blocks (exit 0, no warning)', () => {
    const result = spawnSync('node', [hookPath], {
      input: 'not valid json',
      encoding: 'utf-8',
      env: { ...process.env, CLAUDE_PROJECT_DIR: tempProjectDir },
    });
    expect(result.status).toBe(0);
    expect(result.stdout.trim()).toBe('');
  });

  it('the warning includes the sequence of recent tools', () => {
    runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
    runHook({ session_id: 's1', tool_name: 'Grep', tool_input: {} });
    runHook({ session_id: 's1', tool_name: 'Glob', tool_input: {} });
    runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
    const r = runHook({ session_id: 's1', tool_name: 'Grep', tool_input: {} });
    const ctx = parseDecision(r.stdout).additionalContext ?? '';
    expect(ctx).toContain('Read');
    expect(ctx).toContain('Grep');
    expect(ctx).toContain('Glob');
    expect(ctx).toContain('→');
  });

  it('state file is created at the expected path', () => {
    runHook({ session_id: 's1', tool_name: 'Read', tool_input: {} });
    const stateFile = path.join(tempProjectDir, '.instar', 'state', 'analysis-paralysis-state.json');
    expect(fs.existsSync(stateFile)).toBe(true);
    const state = JSON.parse(fs.readFileSync(stateFile, 'utf-8'));
    expect(state.recent).toHaveLength(1);
    expect(state.recent[0].tool).toBe('Read');
  });
});
