// safe-git-allow: read-only tracked check — this file runs
// `git ls-files --error-unmatch` to assert the manifest is NOT tracked.
// Index query only; mutates nothing.
import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const MANIFEST_PATH = path.join(ROOT, 'src/data/builtin-manifest.json');

describe('INSTAR_BUILTIN_MANIFEST', () => {
  // src/data/builtin-manifest.json is a GENERATED, gitignored build artifact
  // (produced by `npm run build` → scripts/generate-builtin-manifest.cjs, and
  // regenerated by prepublishOnly before publish). A fresh checkout won't have it
  // until built, so generate it here to keep this test self-sufficient — it's the
  // only test that reads the generated file.
  beforeAll(() => {
    if (!fs.existsSync(MANIFEST_PATH)) {
      execSync('node scripts/generate-builtin-manifest.cjs', { cwd: ROOT });
    }
  });

  it('REGRESSION: the manifest is a gitignored artifact, never a committed baseline', () => {
    // This is the fact that made the old "…is stale — commit the result" message
    // impossible to act on. Asserting it pins the premise the corrected message
    // rests on: if somebody starts TRACKING the artifact, this goes red and the
    // remediation wording (rebuild, don't commit) needs revisiting — at which
    // point a genuine committed-baseline check also becomes possible.
    const tracked = (() => {
      try {
        // Read-only: queries index membership, mutates nothing.
        // (Escape is the per-file marker at the top — the per-callsite
        // `incremental-migration` marker expired 2026-05-03 and is closed to
        // new callsites.)
        execSync('git ls-files --error-unmatch src/data/builtin-manifest.json', {
          cwd: ROOT, stdio: 'pipe',
        });
        return true;
      } catch {
        return false;
      }
    })();

    expect(
      tracked,
      'src/data/builtin-manifest.json is now TRACKED by git. The staleness check above says "rebuild, ' +
        'do NOT commit", which was correct only while this artifact was gitignored. With a committed ' +
        'baseline that advice is wrong AND a real committed-vs-source check becomes possible. Revisit ' +
        'tests/unit/builtin-manifest.test.ts.',
    ).toBe(false);
  });

  it('exists and is valid JSON', () => {
    expect(fs.existsSync(MANIFEST_PATH)).toBe(true);
    const content = fs.readFileSync(MANIFEST_PATH, 'utf-8');
    const manifest = JSON.parse(content);
    expect(manifest.schemaVersion).toBe(1);
    expect(manifest.entryCount).toBeGreaterThan(0);
    expect(typeof manifest.entries).toBe('object');
  });

  it('has consistent entryCount', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
    expect(Object.keys(manifest.entries).length).toBe(manifest.entryCount);
  });

  it('every entry has required fields', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
    const requiredFields = ['id', 'type', 'domain', 'sourcePath', 'contentHash', 'since'];

    for (const [id, entry] of Object.entries(manifest.entries) as [string, any][]) {
      for (const field of requiredFields) {
        expect(entry[field], `Entry ${id} missing field '${field}'`).toBeDefined();
      }
      // ID in key matches ID in value
      expect(entry.id).toBe(id);
    }
  });

  it('entry IDs follow the type:name convention', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));

    for (const id of Object.keys(manifest.entries)) {
      expect(id).toMatch(/^[a-z-]+:[a-z0-9._-]+$/i);
    }
  });

  it('the on-disk build artifact is not older than current source', () => {
    // WHAT THIS DETECTS, AND WHAT IT CANNOT — stated because the old wording
    // got both wrong, and because I first "fixed" it in the wrong direction.
    //
    // It compares the artifact ON DISK against a fresh regeneration. That is a
    // REAL check: a local `src/data/builtin-manifest.json` left over from an
    // earlier build goes red here (observed: on-disk instarVersion 1.3.987 vs
    // 1.3.990 regenerated, with differing contentHashes). Remediation is to
    // REBUILD.
    //
    // What it is NOT:
    //   * NOT a check against a committed baseline. The artifact is GENERATED
    //     and GITIGNORED (.gitignore:87) — absent from git entirely. The old
    //     message said "…is stale — run the generator and commit the result";
    //     the "commit" half is impossible to act on. Corrected below.
    //   * NOT informative on a fresh checkout. `beforeAll` generates the file
    //     when missing, so the comparison is then generate(src) vs
    //     generate(src) — trivially equal. Its power depends entirely on a
    //     PRIOR artifact existing. Green here means "no stale local build was
    //     found", which on CI usually means "there was no local build to be
    //     stale".
    //
    // (Kept from the prior fix: generate to a TEMP path rather than over
    // MANIFEST_PATH, so the check never mutates the artifact it reads and
    // cannot race package-completeness.test.ts, whose build regenerates the
    // same file.)
    const tmpOut = path.join(
      fs.mkdtempSync(path.join(os.tmpdir(), 'builtin-manifest-check-')),
      'builtin-manifest.json',
    );
    try {
      execSync('node scripts/generate-builtin-manifest.cjs', {
        cwd: ROOT,
        env: { ...process.env, INSTAR_BUILTIN_MANIFEST_OUT: tmpOut },
        stdio: 'pipe',
      });

      // NOT "committed" — this is the locally generated artifact on disk.
      // Naming it `committed` was part of what made the old claim look sound.
      const onDisk = fs.readFileSync(MANIFEST_PATH, 'utf-8');
      const regenerated = fs.readFileSync(tmpOut, 'utf-8');

      // Strip generatedAt timestamp for comparison (changes every run)
      const normalize = (s: string) => s.replace(/"generatedAt":\s*"[^"]+"/, '"generatedAt": "NORMALIZED"');

      expect(
        normalize(regenerated),
        'src/data/builtin-manifest.json on disk is STALE relative to current source — REBUILD it ' +
          '(`npm run build`, or `node scripts/generate-builtin-manifest.cjs`). Do NOT try to commit it: ' +
          'it is a generated, gitignored artifact (.gitignore:87), so the old "commit the result" ' +
          'advice could never be followed. If this is red in CI rather than locally, the generator may ' +
          'instead be non-deterministic — compare entry ordering.',
      ).toBe(normalize(onDisk));
    } finally {
      SafeFsExecutor.safeRmSync(path.dirname(tmpOut), {
        recursive: true, force: true,
        operation: 'tests/unit/builtin-manifest.test.ts',
      });
    }
  });

  it('covers all 14 built-in hooks', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));

    const expectedHooks = [
      'hook:session-start',
      'hook:dangerous-command-guard',
      'hook:grounding-before-messaging',
      'hook:compaction-recovery',
      'hook:external-operation-gate',
      'hook:deferral-detector',
      'hook:post-action-reflection',
      'hook:external-communication-guard',
      'hook:scope-coherence-collector',
      'hook:scope-coherence-checkpoint',
      'hook:free-text-guard',
      'hook:claim-intercept',
      'hook:claim-intercept-response',
      'hook:auto-approve-permissions',
    ];

    for (const hookId of expectedHooks) {
      expect(manifest.entries[hookId], `Missing hook: ${hookId}`).toBeDefined();
    }
  });

  it('covers all default jobs', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));

    const jobEntries = Object.keys(manifest.entries).filter(id => id.startsWith('job:'));
    expect(jobEntries.length).toBeGreaterThanOrEqual(17); // 19 total, but at minimum 17 enabled
  });

  it('covers core subsystems', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));

    const expectedSubsystems = [
      'subsystem:server',
      'subsystem:session-manager',
      'subsystem:post-update-migrator',
      'subsystem:scheduler',
      'subsystem:project-mapper',
      'subsystem:backup-manager',
      'subsystem:evolution-manager',
    ];

    for (const sub of expectedSubsystems) {
      expect(manifest.entries[sub], `Missing subsystem: ${sub}`).toBeDefined();
    }
  });

  it('all source paths reference existing files', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));

    for (const [id, entry] of Object.entries(manifest.entries) as [string, any][]) {
      const fullPath = path.join(ROOT, entry.sourcePath);
      expect(fs.existsSync(fullPath), `Entry ${id} references missing file: ${entry.sourcePath}`).toBe(true);
    }
  });
});
