/**
 * Regression test — every hook generated by a PostUpdateMigrator `get*Hook()`
 * method must PARSE as valid JavaScript. Closes the bug class that shipped a
 * stray `})();` in `getActionClaimFollowthroughHook` (2026-06-17): the hook had
 * an unbalanced IIFE close, so `node` rejected it with
 * `SyntaxError: Unexpected token '}'` on EVERY Stop-hook fire, fleet-wide.
 *
 * Why a NEW test rather than extending no-bare-require-in-generated-hooks.test.ts:
 * that test is a SOURCE scan for one specific forbidden pattern (bare top-level
 * `require`). It never actually parses the generated content, so a plain syntax
 * typo sails straight past it — which is exactly how the `})();` bug shipped.
 *
 * This test GENERATES each hook (calls the real `get*Hook()` method, so any
 * `${...}` interpolation is resolved to its real value) and runs `node --check`
 * on the result. `node --check` is the ground truth for "will this hook load at
 * all" — the same check the live Claude Code runtime implicitly performs when it
 * spawns the hook. A hook that fails this would crash on every fire.
 *
 * STRUCTURAL prevention: this test fails CI before a broken hook can re-ship.
 */

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { PostUpdateMigrator } from '../../src/core/PostUpdateMigrator.js';

function newMigrator(projectDir: string): PostUpdateMigrator {
  return new PostUpdateMigrator({
    projectDir,
    stateDir: path.join(projectDir, '.instar'),
    port: 4042,
    hasTelegram: true,
    projectName: 'test',
  });
}

/**
 * Discover every `get*Hook` generator method on the prototype. Reflection over
 * the prototype keeps the test in lockstep with the source — a newly-added hook
 * generator is automatically covered, no allowlist to maintain.
 */
function discoverHookGenerators(migrator: PostUpdateMigrator): string[] {
  const proto = Object.getPrototypeOf(migrator);
  const names = Object.getOwnPropertyNames(proto).filter(
    (n) => /^get[A-Z][A-Za-z]*Hook$/.test(n) && typeof (migrator as unknown as Record<string, unknown>)[n] === 'function',
  );
  return [...new Set(names)].sort();
}

/** Only JS hooks are parse-checked by node; .sh/.py generators are skipped here. */
function looksLikeJs(content: string): boolean {
  const head = content.slice(0, 200);
  if (/^#!.*\b(bash|sh)\b/.test(head)) return false;
  if (/^#!.*python/.test(head)) return false;
  // node shebang, or no shebang but JS-ish content
  return /^#!.*node/.test(head) || /\b(process|require|await import|const|function|=>)\b/.test(head);
}

describe('PostUpdateMigrator hook generators — generated content PARSES (regression for the 2026-06-17 stray-IIFE crash)', () => {
  const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-genhooks-'));
  const migrator = newMigrator(tmpRoot);
  const generators = discoverHookGenerators(migrator);

  it('discovers the hook generator methods (sanity)', () => {
    expect(generators.length).toBeGreaterThan(15);
    expect(generators).toContain('getActionClaimFollowthroughHook');
    expect(generators).toContain('getStopGateRouterHook');
  });

  for (const name of generators) {
    it(`${name}: generated JS hook parses under \`node --check\``, () => {
      const content = (migrator as unknown as Record<string, () => unknown>)[name]();
      expect(typeof content).toBe('string');
      const src = content as string;
      if (!looksLikeJs(src)) return; // shell/python generator — out of scope for node parse

      const tmpFile = path.join(tmpRoot, `${name}.js`);
      fs.writeFileSync(tmpFile, src, 'utf-8');
      try {
        execFileSync('node', ['--check', tmpFile], { stdio: 'pipe' });
      } catch (err: unknown) {
        const stderr = (err as { stderr?: Buffer }).stderr?.toString() ?? String(err);
        throw new Error(
          `${name} emits a hook that FAILS \`node --check\` — it would crash on every fire ` +
            `(the 2026-06-17 stray-\`})();\` class). Parser output:\n${stderr}`,
        );
      }
    });
  }
});
