// safe-git-allow: test-tmpdir-cleanup — afterEach removes per-test mkdtempSync tmpdir; SafeFsExecutor migration tracked separately.
/**
 * Unit tests for IdentityRenderer (Tier 1.D).
 *
 * Verifies:
 *   - Render produces CLAUDE.md, AGENTS.md, GEMINI.md shadows.
 *   - Banner is prepended to every shadow.
 *   - Source resolution prefers .instar/AGENT.md, falls back to root.
 *   - Framework subset only writes requested shadows.
 *   - Detect-from-shadow finds the active framework for legacy installs.
 *   - Bootstrap from CLAUDE.md creates AGENT.md and strips banner.
 *
 * Uses tmpdirs throughout so tests don't touch the real filesystem
 * permanently.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  renderIdentity,
  detectFrameworkFromShadowFiles,
  bootstrapAgentMdFromShadow,
  ensureFrameworkIdentityFile,
  FRAMEWORK_SHADOW_FILES,
  IdentityRendererError,
} from '../../src/core/IdentityRenderer.js';

let tmp: string;

beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'identity-renderer-'));
});

afterEach(() => {
  fs.rmSync(tmp, { recursive: true, force: true });
});

describe('renderIdentity', () => {
  it('writes all framework shadows when no subset is specified', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(
      path.join(tmp, '.instar', 'AGENT.md'),
      '# Agent identity\n\nHello.\n',
    );

    const result = renderIdentity({ projectDir: tmp });

    // Round-17: the invariant is one shadow per DISTINCT FILENAME, not per
    // framework. Several frameworks share a shadow file — codex, grok and pi
    // all read the `.agents` convention's AGENTS.md — so a per-framework count
    // would demand the renderer write the same path repeatedly, which is
    // exactly the clobbering bug this replaced (last writer won, and codex
    // agents silently lost their banner and continuation appendix).
    const distinctFilenames = new Set(Object.values(FRAMEWORK_SHADOW_FILES));
    expect(result.shadowsWritten.length).toBe(distinctFilenames.size);
    // Still the load-bearing half: EVERY mapped framework's file must exist.
    for (const filename of Object.values(FRAMEWORK_SHADOW_FILES)) {
      expect(fs.existsSync(path.join(tmp, filename))).toBe(true);
    }
    // And no path may be written twice — a duplicate here IS the clobber.
    expect(new Set(result.shadowsWritten).size).toBe(result.shadowsWritten.length);
    // CONTROL: the grouping must not have quietly dropped a framework. Every
    // requested framework is either written (via its file) or skipped.
    expect(result.skipped).toEqual([]);
  });

  it('prepends an auto-generation banner to every shadow', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Hi\n\nBody.\n');

    renderIdentity({ projectDir: tmp });

    for (const filename of Object.values(FRAMEWORK_SHADOW_FILES)) {
      const content = fs.readFileSync(path.join(tmp, filename), 'utf-8');
      expect(content).toMatch(/AUTO-GENERATED by Instar/);
      expect(content).toMatch(/Do NOT hand-edit/);
      expect(content).toContain('# Hi\n\nBody.');
    }
  });

  it('mentions the framework name in each shadow banner', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), 'body');

    renderIdentity({ projectDir: tmp });

    const claudeContent = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    const codexContent = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(claudeContent).toContain('Framework: claude-code');
    expect(codexContent).toContain('Framework: codex-cli');
  });

  it('respects an explicit frameworks subset', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), 'body');

    renderIdentity({ projectDir: tmp, frameworks: ['codex-cli'] });

    expect(fs.existsSync(path.join(tmp, 'CLAUDE.md'))).toBe(false);
    expect(fs.existsSync(path.join(tmp, 'AGENTS.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'GEMINI.md'))).toBe(false);
  });

  it('falls back to root AGENT.md when .instar/AGENT.md is absent', () => {
    fs.writeFileSync(path.join(tmp, 'AGENT.md'), '# Root identity');
    const result = renderIdentity({ projectDir: tmp });
    expect(result.source).toBe(path.join(tmp, 'AGENT.md'));
    expect(fs.existsSync(path.join(tmp, 'CLAUDE.md'))).toBe(true);
  });

  it('prefers .instar/AGENT.md when both exist', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Canonical');
    fs.writeFileSync(path.join(tmp, 'AGENT.md'), '# Root duplicate');

    const result = renderIdentity({ projectDir: tmp });
    expect(result.source).toBe(path.join(tmp, '.instar', 'AGENT.md'));
    const claudeContent = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(claudeContent).toContain('# Canonical');
    expect(claudeContent).not.toContain('Root duplicate');
  });

  it('throws IdentityRendererError when no source is found', () => {
    expect(() => renderIdentity({ projectDir: tmp })).toThrow(IdentityRendererError);
  });

  it('skips unknown framework names without throwing', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), 'body');

    const result = renderIdentity({
      projectDir: tmp,
      frameworks: ['claude-code', 'unknown-framework'],
    });
    expect(result.shadowsWritten.length).toBe(1);
    expect(result.skipped).toContain('unknown-framework');
  });

  it('honors an explicit sourcePath override', () => {
    const customSource = path.join(tmp, 'custom-identity.md');
    fs.writeFileSync(customSource, '# Custom');

    const result = renderIdentity({
      projectDir: tmp,
      sourcePath: customSource,
      frameworks: ['claude-code'],
    });
    expect(result.source).toBe(customSource);
    expect(fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8')).toContain('# Custom');
  });
});

describe('detectFrameworkFromShadowFiles', () => {
  it('returns null when no shadow file exists', () => {
    expect(detectFrameworkFromShadowFiles(tmp)).toBeNull();
  });

  it('detects claude-code when CLAUDE.md exists', () => {
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), 'legacy claude content');
    expect(detectFrameworkFromShadowFiles(tmp)).toBe('claude-code');
  });

  it('detects codex-cli when only AGENTS.md exists', () => {
    fs.writeFileSync(path.join(tmp, 'AGENTS.md'), 'codex content');
    expect(detectFrameworkFromShadowFiles(tmp)).toBe('codex-cli');
  });
});

describe('bootstrapAgentMdFromShadow', () => {
  it('writes AGENT.md from CLAUDE.md content for legacy installs', () => {
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), '# Legacy agent\n\nBody.\n');
    const result = bootstrapAgentMdFromShadow(tmp);
    expect(result).toBe(path.join(tmp, '.instar', 'AGENT.md'));
    const content = fs.readFileSync(result!, 'utf-8');
    expect(content).toContain('# Legacy agent');
    expect(content).toContain('Body.');
  });

  it('strips the auto-generation banner from the shadow before writing', () => {
    const shadow = [
      '<!--',
      '  AUTO-GENERATED by Instar',
      '-->',
      '',
      '# Real content',
    ].join('\n');
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), shadow);

    const result = bootstrapAgentMdFromShadow(tmp);
    const content = fs.readFileSync(result!, 'utf-8');
    expect(content).not.toContain('AUTO-GENERATED by Instar');
    expect(content).toContain('# Real content');
  });

  it('returns null when no shadow file is found', () => {
    expect(bootstrapAgentMdFromShadow(tmp)).toBeNull();
  });

  it('creates the .instar directory if it does not exist', () => {
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), '# X');
    expect(fs.existsSync(path.join(tmp, '.instar'))).toBe(false);
    bootstrapAgentMdFromShadow(tmp);
    expect(fs.existsSync(path.join(tmp, '.instar'))).toBe(true);
  });
});

describe('ensureFrameworkIdentityFile', () => {
  it('no-ops when the framework shadow already exists', () => {
    fs.writeFileSync(path.join(tmp, 'AGENTS.md'), '# hand-authored');
    const result = ensureFrameworkIdentityFile(tmp, 'codex-cli');
    expect(result).toBeNull();
    // Existing file must not be overwritten
    expect(fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8')).toBe('# hand-authored');
  });

  it('renders AGENTS.md from AGENT.md when codex shadow is missing', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Canonical identity');
    const result = ensureFrameworkIdentityFile(tmp, 'codex-cli');
    expect(result).toBe(path.join(tmp, 'AGENTS.md'));
    const content = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(content).toContain('# Canonical identity');
    expect(content).toContain('AUTO-GENERATED by Instar');
  });

  it('bootstraps AGENT.md from legacy CLAUDE.md then renders AGENTS.md (the live-test scenario)', () => {
    // Legacy install: CLAUDE.md exists, AGENT.md does not, AGENTS.md does not.
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), '# Legacy project');
    expect(fs.existsSync(path.join(tmp, '.instar', 'AGENT.md'))).toBe(false);

    const result = ensureFrameworkIdentityFile(tmp, 'codex-cli', {
      stateDir: path.join(tmp, '.instar'),
    });
    expect(result).toBe(path.join(tmp, 'AGENTS.md'));
    // AGENT.md bootstrapped from CLAUDE.md
    expect(fs.existsSync(path.join(tmp, '.instar', 'AGENT.md'))).toBe(true);
    // AGENTS.md rendered with banner + content
    const agentsMd = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(agentsMd).toContain('# Legacy project');
    expect(agentsMd).toContain('AUTO-GENERATED by Instar');
  });

  it('returns null when no canonical source can be located or bootstrapped', () => {
    // Empty tmp — no AGENT.md, no shadow files
    const result = ensureFrameworkIdentityFile(tmp, 'codex-cli');
    expect(result).toBeNull();
    expect(fs.existsSync(path.join(tmp, 'AGENTS.md'))).toBe(false);
  });

  it('returns null for an unknown framework', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# X');
    const result = ensureFrameworkIdentityFile(tmp, 'unknown-framework');
    expect(result).toBeNull();
  });

  it('is idempotent — calling twice does not double-write or error', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# X');
    const first = ensureFrameworkIdentityFile(tmp, 'codex-cli');
    expect(first).toBe(path.join(tmp, 'AGENTS.md'));
    const second = ensureFrameworkIdentityFile(tmp, 'codex-cli');
    expect(second).toBeNull(); // shadow now exists, no-op
  });

  describe('appendTelegramRelayBlock', () => {
    it('appends the relay section to a freshly rendered AGENTS.md when requested', () => {
      fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
      fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Agent\n\nBody.');
      ensureFrameworkIdentityFile(tmp, 'codex-cli', { appendTelegramRelayBlock: true });
      const out = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      expect(out).toContain('## Telegram Relay (MANDATORY)');
      // Gap 4: the relay appendix now points at the framework-neutral
      // .instar/scripts/ path (works for Codex/Gemini), with a documented
      // .claude/scripts/ fallback note for older installs.
      expect(out).toContain("cat <<'EOF' | .instar/scripts/telegram-reply.sh N");
      expect(out).toContain('.claude/scripts/telegram-reply.sh');
      expect(out).toContain('Codex CLI specifically:');
    });

    it('appends a Claude-specific note when rendering CLAUDE.md', () => {
      fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
      fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Agent\n\nBody.');
      ensureFrameworkIdentityFile(tmp, 'claude-code', { appendTelegramRelayBlock: true });
      const out = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
      expect(out).toContain('## Telegram Relay (MANDATORY)');
      expect(out).toContain('Claude Code specifically:');
    });

    it('re-renders an existing shadow when the relay block is missing and the caller asks for it', () => {
      fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
      fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Agent\n\nBody.');
      ensureFrameworkIdentityFile(tmp, 'codex-cli');
      const before = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      expect(before).not.toContain('Telegram Relay');
      ensureFrameworkIdentityFile(tmp, 'codex-cli', { appendTelegramRelayBlock: true });
      const after = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      expect(after).toContain('## Telegram Relay (MANDATORY)');
    });

    it('skips re-render when the existing shadow already has the relay appendix', () => {
      fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
      fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Agent\n\nBody.');
      ensureFrameworkIdentityFile(tmp, 'codex-cli', { appendTelegramRelayBlock: true });
      const after1 = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      const result = ensureFrameworkIdentityFile(tmp, 'codex-cli', { appendTelegramRelayBlock: true });
      expect(result).toBeNull();
      const after2 = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      expect(after2).toBe(after1);
    });

    it('does NOT append the relay block when option is false (back-compat)', () => {
      fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
      fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Agent\n\nBody.');
      ensureFrameworkIdentityFile(tmp, 'codex-cli');
      const out = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
      expect(out).not.toContain('Telegram Relay');
    });
  });
});

describe('round-18: the PRODUCTION spawn path, not just renderIdentity directly', () => {
  it('ensureFrameworkIdentityFile preserves a sibling framework\'s appendix', () => {
    // Round-17 grouped renderIdentity by filename and tested it THERE. But
    // production reaches it through ensureFrameworkIdentityFile, which passed
    // `frameworks: [framework]` — and grouping a one-element list is a no-op.
    // So the codex clobber the round-17 fix was written to stop still happened
    // on every spawn. A fix verified on a path production does not take is the
    // same shape as a live proof whose input is narrower than production.
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Ident\n\nBody.\n');

    // Establish the codex-owned shared file first.
    renderIdentity({ projectDir: tmp, frameworks: ['codex-cli'] });
    const before = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(before).toContain('Framework: codex-cli');

    // Now a grok spawn on the same agent, through the PRODUCTION entry point.
    // appendTelegramRelayBlock: true mirrors production — server.ts passes it
    // unconditionally on every Telegram spawn, and it is what makes the
    // existing-file guard fall through to the re-render (the clobber path).
    ensureFrameworkIdentityFile(tmp, 'grok-build', {
      stateDir: path.join(tmp, '.instar'),
      appendTelegramRelayBlock: true,
    });

    const after = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    // Both frameworks must be named — the file serves both.
    expect(after).toContain('codex-cli');
    expect(after).toContain('grok-build');
  });

  it('a hookless framework is never told a SessionStart hook covers it', () => {
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Ident\n\nBody.\n');

    renderIdentity({
      projectDir: tmp,
      frameworks: ['grok-build'],
      appendTelegramRelayBlock: true,
    });
    const grokShadow = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    // The predicate enumerated codex+gemini, so the frameworks added later
    // rendered the Claude branch and were told they have a hook they lack.
    expect(grokShadow).not.toContain('the SessionStart hook reinforces this');

    // CONTROL: claude-code, which genuinely HAS the hook, still gets that line.
    // Without this the assertion above would be satisfied by removing the
    // branch entirely.
    renderIdentity({
      projectDir: tmp,
      frameworks: ['claude-code'],
      appendTelegramRelayBlock: true,
    });
    expect(fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8'))
      .toContain('the SessionStart hook reinforces this');
  });
});

describe('round-19: shadow membership is the AGENT\'s frameworks, not the global map', () => {
  it('a codex-only agent is never told about frameworks it did not enable', () => {
    // Round-18 grouped by filename (correct) but drew members from the global
    // map (wrong), so a codex agent that never opted into anything had
    // grok-build and pi-cli named in its own identity file — a dark-ship break
    // against "an agent that does not opt in is byte-identically unaffected".
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Ident\n\nBody.\n');

    ensureFrameworkIdentityFile(tmp, 'codex-cli', {
      stateDir: path.join(tmp, '.instar'),
      appendTelegramRelayBlock: true,
    });
    const shadow = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(shadow).toContain('codex-cli');
    expect(shadow).not.toContain('grok-build');
    expect(shadow).not.toContain('pi-cli');
  });

  it('CONTROL: an agent that DID enable both gets one file naming both', () => {
    // Without this the assertion above would be satisfied by reverting the
    // grouping entirely, which is the clobbering bug round 18 fixed.
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Ident\n\nBody.\n');

    ensureFrameworkIdentityFile(tmp, 'codex-cli', {
      stateDir: path.join(tmp, '.instar'),
      appendTelegramRelayBlock: true,
      enabledFrameworks: ['codex-cli', 'grok-build'],
    });
    const shadow = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(shadow).toContain('codex-cli');
    expect(shadow).toContain('grok-build');
  });

  it('a hookless framework is addressed by ITS OWN name, never another\'s', () => {
    // The predicate was widened in round 18 because "an enumeration is what
    // went stale"; the enumeration inside the branch was left, defaulting to
    // "Codex CLI" — so grok agents were addressed as Codex.
    fs.mkdirSync(path.join(tmp, '.instar'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.instar', 'AGENT.md'), '# Ident\n\nBody.\n');

    renderIdentity({ projectDir: tmp, frameworks: ['grok-build'], appendTelegramRelayBlock: true });
    const shadow = fs.readFileSync(path.join(tmp, 'AGENTS.md'), 'utf-8');
    expect(shadow).toContain('Grok Build specifically');
    expect(shadow).not.toContain('Codex CLI specifically');
  });
});
